#!/bin/bash
#!
#! SLURM job for SAE (test)  for Wilkes3 (AMD EPYC 7763, ConnectX-6, A100)
#! Last updated: Thu 14 Apr 2022
#!

#!#############################################################
#!#### Modify the options in this section as appropriate ######
#!#############################################################

#! sbatch directives begin here ###############################
#! Name of the job:
#SBATCH -J dk538-icovae
#! Which project should be charged (NB Wilkes2 projects end in '-GPU'):
#SBATCH -A MRC-BSU-SL2-GPU
#! How many whole nodes should be allocated?
#SBATCH --nodes=1
#! How many (MPI) tasks will there be in total?
#! Note probably this should not exceed the total number of GPUs in use.
#SBATCH --ntasks=1
#! Specify the number of GPUs per node (between 1 and 4; must be 4 if nodes>1).
#! Note that the job submission script will enforce no more than 32 cpus per GPU.
#SBATCH --gres=gpu:1
#! How much wallclock time will be required?
#SBATCH --time=06:00:00
#! What types of email messages do you wish to receive?
#SBATCH --mail-type=begin
#SBATCH --mail-type=end
#SBATCH --mail-type=fail
#SBATCH --mail-user=dom.kirkham@mrc-bsu.cam.ac.uk
#SBATCH --output=/home/dk538/rds/hpc-work/graphdep/slurm_out/icovae_hopt/%j.out
#! Uncomment this to prevent the job from being requeued (e.g. if
#! interrupted by node failure or system downtime):
#SBATCH --no-requeue

#! Do not change:
#SBATCH -p ampere

#! sbatch directives end here (put any additional directives above this line)

#! Notes:
#! Charging is determined by GPU number*walltime. 

#! Number of nodes and tasks per node allocated by SLURM (do not change):
numnodes=$SLURM_JOB_NUM_NODES
numtasks=$SLURM_NTASKS
mpi_tasks_per_node=$(echo "$SLURM_TASKS_PER_NODE" | sed -e  's/^\([0-9][0-9]*\).*$/\1/')
#! ############################################################
#! Modify the settings below to specify the application's environment, location 
#! and launch method:

#! Optionally modify the environment seen by the application
#! (note that SLURM reproduces the environment at submission irrespective of ~/.bashrc):
. /etc/profile.d/modules.sh                # Leave this line (enables the module command)
module purge                               # Removes all modules still loaded
module load rhel8/default-amp              # REQUIRED - loads the basic environment

#! Insert additional module load commands after this line if needed:
source /home/dk538/.bashrc
module load cuda/11.8 cudnn/8.9_cuda-11.8 hdf5/1.8.2
conda activate slurm-torch-2

#! Full path to application executable: 
application="python -u ./scripts/icovae_hopt.py"

#! Run options for the application:
#options="-dataset depmap_gdsc_transneo -target RCB.score -constraints MCL1 PSMC1 FANCF RAD1 PPM1D ESR1 ERBB2 CDKN2A TP53 IGF1R FGFR2 CCNE1 PIK3CA GATA3 MAP3K1 EGFR --cuda --experiment tnbc"
#options="-dataset sim1 -target y_0 -constraints s_0 s_1 s_2 s_3 s_4 s_5 s_6 s_7 s_8 s_9 s_10 s_11 s_12 s_13 s_14 s_15 --cuda --experiment none --newstudy"
#options="-dataset depmap_gdsc_scanb_tcga -target BCFi_5Y -constraints MCL1 PSMC1 FANCF RAD1 PPM1D ESR1 ERBB2 CDKN2A TP53 IGF1R FGFR2 CCNE1 PIK3CA GATA3 MAP3K1 EGFR --confounders AGE ER HER2 LN SIZE --cuda --experiment tcga_5y"
options="-dataset depmap_gdsc -target AZD5153 --cuda --experiment h16 --test --newstudy"

#! Work directory (i.e. where the job will run):
workdir="$SLURM_SUBMIT_DIR"  # The value of SLURM_SUBMIT_DIR sets workdir to the directory
                             # in which sbatch is run.

#! Are you using OpenMP (NB this is unrelated to OpenMPI)? If so increase this
#! safe value to no more than 128:
export OMP_NUM_THREADS=1

#! Number of MPI tasks to be started by the application per node and in total (do not change):
np=$[${numnodes}*${mpi_tasks_per_node}]

#! Choose this for a pure shared-memory OpenMP parallel program on a single node:
#! (OMP_NUM_THREADS threads will be created):
CMD="$application $options"

#! Choose this for a MPI code using OpenMPI:
#CMD="mpirun -npernode $mpi_tasks_per_node -np $np $application $options"


###############################################################
### You should not have to change anything below this line ####
###############################################################

cd $workdir
echo -e "Changed directory to `pwd`.\n"

JOBID=$SLURM_JOB_ID

echo -e "JobID: $JOBID\n======"
echo "Time: `date`"
echo "Running on master node: `hostname`"
echo "Current directory: `pwd`"

if [ "$SLURM_JOB_NODELIST" ]; then
        #! Create a machine file:
        export NODEFILE=`generate_pbs_nodefile`
        cat $NODEFILE | uniq > machine.file.$JOBID
        echo -e "\nNodes allocated:\n================"
        echo `cat machine.file.$JOBID | sed -e 's/\..*$//g'`
fi

echo -e "\nnumtasks=$numtasks, numnodes=$numnodes, mpi_tasks_per_node=$mpi_tasks_per_node (OMP_NUM_THREADS=$OMP_NUM_THREADS)"

echo -e "\nExecuting command:\n==================\n$CMD\n"

eval $CMD 
